### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by KenEucker** [TeamWertarbyte/material-ui-toggle-icon#21]
Does this component support Typescript? I am running into errors when trying to render the component I have using your exmaple.

I am using the following `ToggleField.tsx` component in my project:

```ts
import * as React from "react"
import ToggleIcon from "material-ui-toggle-icon"
import IconButton from "@material-ui/core/IconButton"
import Visibility from "@material-ui/icons/Visibility"
import VisibilityOff from "@material-ui/icons/VisibilityOff"

interface ToggleIconButtonProps {
    on: boolean
    onClick: Function
}
export default class ToggleIconButton extends React.Component<ToggleIconButtonProps, {}> {
  state = { on: this.props.on }

  render = () => (
    <IconButton onClick={() => { this.setState((state: ToggleIconButtonProps) => ({ on: !state.on })) ; this.props.onClick() }}>
      <ToggleIcon
        on={this.state.on}
        onIcon={<Visibility />}
        offIcon={<VisibilityOff />}
      />
    </IconButton>)
}
```

And I am getting the following errors when trying to use that component:
```bash
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476)
    at Object.useContext (react.development.js:1484)
    at useTheme (useTheme.js:4)
    at useStyles (makeStyles.js:222)
    at WithStyles (withStyles.js:55)
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)
    at beginWork (react-dom.development.js:19098)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
resolveDispatcher @ react.development.js:1476
useContext @ react.development.js:1484
useTheme @ useTheme.js:4
useStyles @ makeStyles.js:222
WithStyles @ withStyles.js:55
renderWithHooks @ react-dom.development.js:14985
updateForwardRef @ react-dom.development.js:17044
beginWork @ react-dom.development.js:19098
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22779
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
5react-dom.development.js:20085 The above error occurred in the <WithStyles(ToggleIcon)> component:

    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:3774:31)
    at span
    at button
    at ButtonBase (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:17792:22)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at IconButton (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:27540:27)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at ToggleIconButton (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:190108:9)
    at div
    at Grid (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:25791:35)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at div
    at ButtonBase (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:17792:22)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at li
    at ListItem (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:29945:33)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at ul
    at List (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:29704:24)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at li
    at ListItem (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:29945:33)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at ul
    at List (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:29704:24)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at div
    at StyledComponent (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52564:28)
    at div
    at Paper (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:33574:23)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at Transition (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:153066:30)
    at Grow (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:26526:24)
    at Unstable_TrapFocus (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:45331:24)
    at div
    at Portal (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:34641:24)
    at Modal (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:31855:75)
    at Popover (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:33788:22)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at SubAccountSelectField (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:189920:34)
    at label
    at FormControlLabel (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:24968:23)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at div
    at FormGroup (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:25141:23)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at fieldset
    at FormControl (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:24558:24)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at form
    at EditEventListItem (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:189382:57)
    at div
    at ButtonBase (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:17792:22)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at ListItem (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:29945:33)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at EventListing (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:189507:70)
    at ul
    at List (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:29704:24)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at div
    at div
    at Grid (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:25791:35)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at div
    at Grid (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:25791:35)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at div
    at EventsList (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:189642:51)
    at div
    at EventsListContainer (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:189743:53)
    at div
    at Grid (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:25791:35)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at Events (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:192028:9)
    at WithStyles (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:52762:31)
    at Route (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:140607:29)
    at Switch (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:140813:29)
    at Routes
    at div
    at div
    at div
    at LoadingOverlayWrapper (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:134980:5)
    at LoadingPanel (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:190594:103)
    at InitialDataLoader (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:190263:53)
    at ThemeProvider (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:51729:24)
    at Router (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:140236:30)
    at HashRouter (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:139890:35)
    at LighthouseContextProvider (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:190550:39)
    at StylesProvider (http://localhost:8080/bundle.b7f7c28361cba4682f57.js:51562:24)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20085
update.callback @ react-dom.development.js:20118
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20736
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react.development.js:1476 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476)
    at Object.useContext (react.development.js:1484)
    at useTheme (useTheme.js:4)
    at useStyles (makeStyles.js:222)
    at WithStyles (withStyles.js:55)
    at renderWithHooks (react-dom.development.js:14985)
    at updateForwardRef (react-dom.development.js:17044)
    at beginWork (react-dom.development.js:19098)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
resolveDispatcher @ react.development.js:1476
useContext @ react.development.js:1484
useTheme @ useTheme.js:4
useStyles @ makeStyles.js:222
WithStyles @ withStyles.js:55
renderWithHooks @ react-dom.development.js:14985
updateForwardRef @ react-dom.development.js:17044
beginWork @ react-dom.development.js:19098
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22779
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

Thanks in advance for your help!

**Comment by leMaik** [comment]
This isn't related to TypeScript and I'm very sure we don't break the rules of hooks. Do your React and React DOM versions match?
